TINYCRYPT_DIR ?= $(PWD)/../tinycrypt/lib
TINYCRYPT_LIB ?= $(TINYCRYPT_DIR)/libtinycrypt.a

CFLAGS += -DCRYPTO_TINYCRYPT

TINYCRYPT_INCLUDE ?= -I$(TINYCRYPT_DIR)/include

CRYPTOSRC = $(SRC_DIR)/crypt/tinycrypt.c
CFLAGS_CRYPTO += $(TINYCRYPT_INCLUDE)
LDFLAGS_CRYPTO += $(TINYCRYPT_LIB)
